email:
  sender:
    token: ${MAIL_SENDER_TOKEN}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: email-sender-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: org.roadmap.trackeremailsender.models.EmailLetterModel
  mail:
    host: smtp.gmail.com
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
kafka:
  topic: ${KAFKA_TOPIC_NAME}


server:
  port: 8085